package com.pharmacy.pms.model.enums;

public enum ExpenseCategory {
    RENT,
    UTILITIES,
    SALARIES_PAYROLL,
    TRANSPORT_LOGISTICS,
    LICENSES_REGULATORY,
    MAINTENANCE_REPAIRS,
    PACKAGING_CONSUMABLES,
    MARKETING_ADVERTISING,
    STOCK_LOSS_WRITE_OFF,
    TAXES_LEVIES,
    OFFICE_SUPPLIES,
    MISCELLANEOUS
}
